name: Deploy Blazor WebAssembly to GitHub Pages

on:
  push:
    branches:
      - main  # твоя основная ветка

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 9.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Replace base href for GitHub Pages
        run: |
          sed -i 's|<base href="/">|<base href="/bff_groups/">|' ./bff_groups/wwwroot/index.html

      - name: Publish Blazor WebAssembly
        run: dotnet publish bff_groups -c Release -o ./publish

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./publish/wwwroot
          publish_branch: gh-pages
